"""Add openai_thread_id to threads

Revision ID: cda3d7ebeb67
Revises: 64be6aac5fe1
Create Date: 2024-12-16 03:30:31.901303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda3d7ebeb67'
down_revision = '64be6aac5fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_thread_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_column('openai_thread_id')

    # ### end Alembic commands ###
